WebsiteTheFaceShop/Areas/Admin/Controllers/QL_DonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteTheFaceShop.Filters;
using WebsiteTheFaceShop.Models;
using WebsiteTheFaceShop.Identity;

namespace WebsiteTheFaceShop.Areas.Admin.Controllers
{
    //Áp dụng kiểm tra quyền cho toàn bộ controller
    [KiemTraQuyenTruyCap]
    public class QL_DonHangController : Controller
    {
        // GET: Admin/QL_DonHang
        public ActionResult TrangChu()
        {
            ViewBag.TongDon = TongDonHang();
            ViewBag.TongDoanhThu = TongDoanhThu();
            ViewBag.TongAccount = TongAccount();
            ViewBag.TongSanPham = TongSP();
            return View();
        }

        public ActionResult XemChiTiet(int id)
        {
            DataModelDbContext db = new DataModelDbContext();
            List<CTHOADON> cthd = db.CTHOADONs.Where(row => row.MaHD == id).ToList();
            return View(cthd);
        }

        public int TongDonHang()
        {
            DataModelDbContext db = new DataModelDbContext();
            int tongDDH = db.HOADONs.Count();
            return tongDDH;
        }

        public int TongAccount()
        {
            AppDbContext db = new AppDbContext();
            int tongUser = db.Users.Count();
            return tongUser;
        }

        public decimal TongDoanhThu()
        {
            DataModelDbContext db = new DataModelDbContext();

            decimal tongDT = 0; // Khởi tạo tổng doanh thu ban đầu là 0

            foreach (var hd in db.CTHOADONs)
            {
                if (hd.DonGia.HasValue && hd.SoLuong.HasValue)
                {
                    tongDT += hd.DonGia.Value * hd.SoLuong.Value;
                }
            }

            return tongDT;
        }

        public int TongSP()
        {
            DataModelDbContext db = new DataModelDbContext();
            int tongSP = db.SANPHAMs.Count();
            return tongSP;
        }
    }
}

WebsiteTheFaceShop/Areas/Admin/Controllers/QL_SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteTheFaceShop.Models;
using WebsiteTheFaceShop.Filters;
using System.Data;
using System.IO;

namespace WebsiteTheFaceShop.Areas.Admin.Controllers
{
    //Áp dụng kiểm tra quyền cho toàn bộ controller
    [KiemTraQuyenTruyCap]
    public class QL_SanPhamController : Controller
    {
        // GET: Admin/QL_SanPham
        public ActionResult TrangChu(string search = "", string SortColumn = "MaSP", string IconClass = "fa-sort-asc", int page = 1)
        {
            DataModelDbContext db = new DataModelDbContext();
            List<SANPHAM> dsSanPham = db.SANPHAMs.Where(row => row.TenSP.Contains(search)).ToList();

            //TÍNH NĂNG TÌM KIẾM SP
            if (dsSanPham.Count == 0)
            {
                ViewBag.Search = search;
                ViewBag.Message = "Sản phẩm không tồn tại.";
            }
            else
            {
                ViewBag.Search = search;
                ViewBag.Message = "";
            }

            //TÍNH NĂNG SẮP XẾP SP
            ViewBag.SortColumn = SortColumn;
            ViewBag.IconClass = IconClass;
            if (SortColumn == "MaSP")
            {
                if (IconClass == "fa-sort-asc")
                    dsSanPham = dsSanPham.OrderBy(row => row.MaSP).ToList();
                else
                    dsSanPham = dsSanPham.OrderByDescending(row => row.MaSP).ToList();
            }
            else if (SortColumn == "TenSP")
            {
                if (IconClass == "fa-sort-asc")
                    dsSanPham = dsSanPham.OrderBy(row => row.TenSP).ToList();
                else
                    dsSanPham = dsSanPham.OrderByDescending(row => row.TenSP).ToList();
            }
            else //sx theo loại   
            {
                if (IconClass == "fa-sort-asc")
                    dsSanPham = dsSanPham.OrderBy(row => row.TenLoai).ToList();
                else
                    dsSanPham = dsSanPham.OrderByDescending(row => row.TenLoai).ToList();
            }

            //TÍNH NĂNG PHÂN TRANG
            int NoOfRecordPerPage = 8;
            int NoOfPages = Convert.ToInt32(Math.Ceiling(Convert.ToDouble(dsSanPham.Count) / Convert.ToDouble(NoOfRecordPerPage)));
            int NoOfRecordToSkip = (page - 1) * NoOfRecordPerPage;
            ViewBag.Page = page;
            ViewBag.NoOfPages = NoOfPages;
            dsSanPham = dsSanPham.Skip(NoOfRecordToSkip).Take(NoOfRecordPerPage).ToList();
            return View(dsSanPham);
        }

        //TÍNH NĂNG THÊM MỚI SP VÀO DATABASE
        public ActionResult ThemSP()
        {
            DataModelDbContext db = new DataModelDbContext();
            ViewBag.TenLoai = db.SANPHAMs.ToList();
            ViewBag.TenThuongHieu = db.SANPHAMs.ToList();
            ViewBag.DanhMuc = db.DANHMUCs.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult ThemSP(SANPHAM sp,HttpPostedFileBase uploadHinh)
        {
            DataModelDbContext db = new DataModelDbContext();

            // Kiểm tra xem thư mục tồn tại chưa, nếu không thì tạo mới
            string uploadFolder = Server.MapPath("~/Content/images");
            if (!Directory.Exists(uploadFolder))
            {
                Directory.CreateDirectory(uploadFolder);
            }

            if (uploadHinh == null)
            {
                ViewBag.ThongBao = "Vui lòng chọn hình ảnh";
                return View();
            }

            if (ModelState.IsValid)
            {
                //Lưu tên file
                var fileName = Path.GetFileName(uploadHinh.FileName);
                //Lưu đường dẫn của file
                var path = Path.Combine(uploadFolder, fileName);
                //Kiểm tra hình bị trùng
                if (System.IO.File.Exists(path))
                {
                    ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                }
                else
                {
                    //lưu hình ảnh vào đường dẫn
                    uploadHinh.SaveAs(path);
                }
                sp.TenHinh = fileName; //Update tên hình vào database
                db.SANPHAMs.Add(sp);
                db.SaveChanges();
            }
            return RedirectToAction("TrangChu");
        }

        //TÍNH NĂNG XEM CHI TIẾT SP
        public ActionResult XemChiTietSP(int id)
        {
            DataModelDbContext db = new DataModelDbContext();
            SANPHAM sanpham = db.SANPHAMs.Where(row => row.MaSP == id).FirstOrDefault();
            if (sanpham != null)
            {
                DANHMUC danhMuc = db.DANHMUCs.Find(sanpham.MaDanhMuc); // Lấy thông tin danh mục
                ViewBag.TenDanhMuc = danhMuc != null ? danhMuc.TenDanhMuc : "Không có danh mục"; // Đảm bảo danh mục tồn tại
            }
            return View(sanpham);
        }

        //TÍNH NĂNG CHỈNH SỬA SP
        public ActionResult ChinhSuaSP(int id)
        {
            DataModelDbContext db = new DataModelDbContext();
            SANPHAM sanpham = db.SANPHAMs.Where(row => row.MaSP == id).FirstOrDefault();
            var distinctLoai = db.SANPHAMs.Select(sp => sp.TenLoai).Distinct().ToList();
            ViewBag.TenLoai = new SelectList(distinctLoai);
            var distinctThuongHieu = db.SANPHAMs.Select(sp => sp.TenThuongHieu).Distinct().ToList();
            ViewBag.TenThuongHieu = new SelectList(distinctThuongHieu);
            ViewBag.DanhMuc = db.DANHMUCs.ToList();
            return View(sanpham);
        }

        [HttpPost]
        public ActionResult ChinhSuaSP(SANPHAM sp, HttpPostedFileBase uploadHinh)
        {
            DataModelDbContext db = new DataModelDbContext();
            SANPHAM sanpham = db.SANPHAMs.Where(row => row.MaSP == sp.MaSP).FirstOrDefault();

            //Cập nhật sản phẩm
            sanpham.TenSP = sp.TenSP;
            sanpham.TenLoai = sp.TenLoai;
            sanpham.TenThuongHieu = sp.TenThuongHieu;
            sanpham.MaDanhMuc = sp.MaDanhMuc;
            sanpham.DonGiaMua = sp.DonGiaMua;
            sanpham.DonGiaBan = sp.DonGiaBan;
            sanpham.SoLuong = sp.SoLuong;
            sanpham.GiamGia = sp.GiamGia;
            sanpham.TenHinh = sp.TenHinh;
            sanpham.MoTa = sp.MoTa;

            string uploadFolder = Server.MapPath("~/Content/images");
            if (!Directory.Exists(uploadFolder))
            {
                Directory.CreateDirectory(uploadFolder);
            }

            if (uploadHinh == null)
            {
                ViewBag.ThongBao = "Vui lòng chọn hình ảnh";
                return View();
            }

            if (uploadHinh != null && uploadHinh.ContentLength > 0)
            {
     
                //Lưu tên file
                var fileName = Path.GetFileName(uploadHinh.FileName);
                //Lưu đường dẫn của file
                var path = Path.Combine(uploadFolder, fileName);
                //Kiểm tra hình bị trùng
                if (System.IO.File.Exists(path))
                {
                    ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                }
                else
                {
                    //lưu hình ảnh vào đường dẫn
                    uploadHinh.SaveAs(path);
                }
                sanpham.TenHinh = fileName;
            }

            db.SaveChanges();

            return RedirectToAction("TrangChu");
        }

        //TÍNH NĂNG XOÁ SP
        public ActionResult XoaSP(int id)
        {
            DataModelDbContext db = new DataModelDbContext();
            SANPHAM sanpham = db.SANPHAMs.Where(row => row.MaSP == id).FirstOrDefault();
            return View(sanpham);
        }

        [HttpPost]
        public ActionResult XoaSP(int id, SANPHAM sp)
        {
            DataModelDbContext db = new DataModelDbContext();
            SANPHAM sanpham = db.SANPHAMs.Where(row => row.MaSP == id).FirstOrDefault();
            db.SANPHAMs.Remove(sanpham);
            db.SaveChanges();
            return RedirectToAction("TrangChu");
        }

        public ActionResult Test()
        {
            return View();
        }
    }
}

WebsiteTheFaceShop/Areas/Admin/Controllers/QL_UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteTheFaceShop.Identity;
using WebsiteTheFaceShop.Filters;

namespace WebsiteTheFaceShop.Areas.Admin.Controllers
{
    //Áp dụng kiểm tra quyền cho toàn bộ controller
    [KiemTrangDangNhap]
    [KiemTraQuyenTruyCap]
    public class QL_UserController : Controller
    {
        // GET: Admin/QL_User
        public ActionResult TrangChu()
        {
            AppDbContext db = new AppDbContext();
            List<AppUser> listUser = db.Users.ToList();
            return View(listUser);
        }
    }
}

WebsiteTheFaceShop/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/root/img/logo.png" rel="icon" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" /> <!--Link lấy icon sx tăng/giảm-->
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/showReview.js"></script>
    <style>
        .lst_custom {
            transition: background 0.5s all ease-in-out;
        }

            .lst_custom:hover {
                background: linear-gradient(90deg,white 50%, #fff1f3 50%);
                background-size: 200% 100%;
                background-position: -100% 0;
                font-weight: bold;
            }

            .lst_custom a {
                padding-left: 0;
                text-decoration: none;
                color: black;
                font-weight: bold;
            }

                .lst_custom a:hover {
                    color: red;
                    padding-left: 20px;
                    transition: 0.3s all ease-in-out;
                }
    </style>
</head>
<body>
    @{
        var modell = 0;
    }
    <div class="container-fluid">

        <!--Left Dashboard-->

        <div class="row">

            <!--Sidebar-->

            <div class="col-2 p-0 m-0" style="min-height: 800px;background-color: #f3d8da;">
                <div class="container-fluid p-0 m-0 w-100">
                    <div class="text-center">
                        <img src="~/root/img/logo.png" class="img-fluid w-50 m-auto my-3" alt="Alternate Text" />
                    </div>

                    <ul class="list-group rounded-0">
                        @*<li class="list-group-item px-4 pt-3 pb-3 lst_custom">@Html.ActionLink("Quản lý Admin", "QLAdmin", "Admin")</li>*@
                        <li class="list-group-item px-4 pt-3 pb-3 lst_custom">@Html.ActionLink("Quản lý Users", "TrangChu", "QL_User")</li>
                        <li class="list-group-item px-4 pt-3 pb-3 lst_custom">@Html.ActionLink("Quản lý đơn hàng", "TrangChu", "QL_DonHang")</li>
                        <li class="list-group-item px-4 pt-3 pb-3 lst_custom">@Html.ActionLink("Quản lý Sản Phẩm", "TrangChu", "QL_SanPham")</li>
                        <li class="list-group-item px-4 pt-3 pb-3 lst_custom">@Html.ActionLink("Trang View User", "TrangChu", "Home", new { Area = "" }, null)</li>

                        @*<li class="list-group-item px-4 pt-3 pb-3 lst_custom"> <a href="/Home/TrangChu"> Trang View User</a>*@
                        <li class="list-group-item px-4 pt-3 pb-3 lst_custom"> <a href="/Account/DangXuat"> ⬅️ Đăng Xuất</a>
                        <li>
                    </ul>

                </div>
            </div>



            <!--Right Dashboard-->

            <div class="col-10" style=" background-color:#fff1f3">

                <!--Header-->

                <div class="container-fluid pt-3" style="background-color:  #fff1f3">
                    <div class="row justify-content-between align-items-center">
                        <div class="col-12">
                            <!--Trường hợp đã đăng nhập thành công-->
                            @if (User.Identity.IsAuthenticated)
                            {
                                <h2 style="color:red ; font-weight:bold">
                                    Hello @User.Identity.Name😘
                                </h2>
                            }
                        </div>

                        @*<div class="col-5">
                                <div class="row align-items-center">
                                    <div class="col-5">
                                        <input class="rounded-2 w-100 " style="height:2rem" type="text" name="search_OrderID" value="" placeholder="Tìm theo mã đơn hàng" />
                                    </div>
                                    <div class="col-4">
                                        <input class="btn btn-outline-success btn-sm rounded-2 w-50" type="button" name="name" value="Search" />
                                    </div>
                                    <div class="col-3">
                                        <span class="me-2 fs-4 mx-3">🔔</span>
                                        <span class="fs-4 bg-dark-subtle rounded-5">🙎‍♂️</span>
                                    </div>
                                </div>
                            </div>*@
                    </div>

                </div>

                <!--Content Body-->
                @RenderBody()


            </div>
        </div>
    </div>

    <!--Footer-->

    @{
        int currentYear = DateTime.Now.Year;
    }

    <div class="container-fluid p-0 m-0 text-center border border-1" style="background-color:#fff1f3">
        <h6 class="p-3 m-0">The Face Shop Admin @currentYear. &#169; Copyright by <span class="text-danger fw-bolder">BLUE SKY TEAM</span>. All Rights Reserved.</h6>
    </div>
    <script>
        $(document).ready(() => {
            $.ajax({
                type: 'GET',
                url: '/api/QL_DonHang',
                success: (responses) => {
                    for (var i = 0; i <= responses.length; i++) {
                        const hdRow = responses[i];
                        const strHTML = '<tr><td>' + hdRow.MaHD + '</td><td>' + hdRow.TenKH + '</td><td>' + hdRow.NgayLap + '</td><td>' + hdRow.SDT + '</td><td>' + hdRow.DiaChi + '</td><td>' + hdRow.Email + '</td><td class="text-center"> <a class="text-decoration-none icon-link-hover fs-5" href="/Admin/QL_DonHang/XemChiTiet/  ' + hdRow.MaHD + '">ℹ️</a></td></tr > ';
                        $('.hdtable').append(strHTML);
                    }
                },
                error: (err) => { console.log(err); }
            });
        });

    </script>


</body>
</html>